BiocManager::install("DESeq2")
library(DESeq2)
#this is based on the vignette for DEseq2 and is "no magic"
#https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html

#import the count matrix as generated by prepDE.py for all the samples to be analyzed
countData <- as.matrix(read.csv("~/bigdata/Slycopersicum/Results_Stringtie/transcript_count_matrix.csv"))
rownames(countData) <- gsub('.{2}$','',gsub('mRNA:','',countData[,1]))
countData <- as.matrix(countData[,-1])
class(countData) <- "numeric"

#import a design matrix, in this case, I'll make it by hand
colData <- data.frame(row.names=c("AC1DPA1", "AC1DPA2", "AC1DPA3", "AC15DPA1", "AC15DPA2", "AC15DPA3"), condition=c(rep("1DPA",3), rep("15DPA", 3)) ,rep=rep(c(1,2,3),2))

#rearrange to a more logical order
countData <- countData[, rownames(colData)]

#made the dataset for analysis
dds <- DESeqDataSetFromMatrix(countData = countData,
                              colData = colData,
                              design = ~ condition)

#Run the actual analysis
dds <- DESeq(dds)
res <- results(dds, alpha=0.05)
summary(res)
  

